- name: Install PostrgreSQL Database installation and configuration 
  hosts: "*"
  become: yes
  tasks:
    - name: Get the File Repository Configuration
      shell: echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
    
    - name: Import the repository signing key
      ansible.builtin.apt_key :
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc 
        state: present

    - name: Update the Package List
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Install Postgress Sql
      apt:
        name: postgresql-12 
        state: present
    
    - name: Install Postgress Client
      apt:
        name: postgresql-client
        state: present
    
    - name: Install Postgress Client-Common
      apt:
        name: postgresql-client-common
        state: present



